http:
  routers:
    uptimekuma-duckdns:
      rule: Host(`upk.matrexdns.duckdns.org`)
      service: uptimekuma
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt-duck

    jellyfin-duckdns:
      rule: Host(`jf.matrexdns.duckdns.org`)
      service: jellyfin
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt-duck

    uptimekuma-dynu:
      rule: Host(`upk.matrex.gleeze.com`)
      service: uptimekuma
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt-dynu

    jellyfin-dynu:
      rule: Host(`jf.matrex.gleeze.com`)
      service: jellyfin
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt-dynu

  services:
    uptimekuma:
      loadBalancer:
        servers:
          - url: http://upk.my.local:3001

    jellyfin:
      loadBalancer:
        servers:
          - url: http://192.168.3.42:8096
