http:
  routers:
    uptimekuma-duckdns:
      rule: Host(`upk.matrexdns.duckdns.org`)
      service: uptimekuma
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt-duck

    jellyfin-duckdns:
      rule: Host(`jf.matrexdns.duckdns.org`)
      service: jellyfin
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt-duck

    uptimekuma-dynu:
      rule: Host(`upk.matrex.gleeze.com`)
      service: uptimekuma
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt-dynu

    jellyfin-dynu:
      rule: Host(`jf.matrex.gleeze.com`)
      service: jellyfin
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt-dynu

    wud-dynu:
      rule: Host(`wud.matrex.gleeze.com`)
      service: wud
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt-dynu

    dp-dynu:
      rule: Host(`dp.matrex.gleeze.com`)
      service: dp
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt-dynu

    home-dynu:
      rule: Host(`home.matrex.gleeze.com`)
      service: home
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt-dynu

    ddns-dynu:
      rule: Host(`ddns.matrex.gleeze.com`)
      service: ddns
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt-dynu

    downtify-dynu:
      rule: Host(`dtify.matrex.gleeze.com`)
      service: downtify
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt-dynu

    adg-dynu:
      rule: Host(`adg.matrex.gleeze.com`)
      service: adg
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt-dynu

    spd-dynu:
      rule: Host(`spd.matrex.gleeze.com`)
      service: spd
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt-dynu

    beszel-dynu:
      rule: Host(`bes.matrex.gleeze.com`)
      service: beszel
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt-dynu

    pialert-dynu:
      rule: Host(`pi.matrex.gleeze.com`)
      service: pialert
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt-dynu

    zima-dynu:
      rule: Host(`zima.matrex.gleeze.com`)
      service: zima
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt-dynu

  services:
    uptimekuma:
      loadBalancer:
        servers:
          - url: http://192.168.3.34:3001

    jellyfin:
      loadBalancer:
        servers:
          - url: http://192.168.3.36:8096

    wud:
      loadBalancer:
        servers:
          - url: http://192.168.3.36:3002

    dp:
      loadBalancer:
        servers:
          - url: http://192.168.3.36:8807

    home:
      loadBalancer:
        servers:
          - url: http://192.168.3.36:3000

    ddns:
      loadBalancer:
        servers:
          - url: http://192.168.3.38:8000

    btop:
      loadBalancer:
        servers:
          - url: http://192.168.3.36:7600

    downtify:
      loadBalancer:
        servers:
          - url: http://192.168.3.36:8582

    adg:
      loadBalancer:
        servers:
          - url: http://192.168.3.32

    spd:
      loadBalancer:
        servers:
          - url: http://192.168.3.35:5216

    beszel:
      loadBalancer:
        servers:
          - url: http://192.168.3.33:8090

    pialert:
      loadBalancer:
        servers:
          - url: http://192.168.3.31

    zima:
      loadBalancer:
        servers:
          - url: http://192.168.3.36:100

    nextcloud:
      loadBalancer:
        servers:
          - url: http://192.168.3.36:8080
