entryPoints:
  web:
    address: ":80"
    transport:
      lifeCycle:
        requestAcceptGraceTimeout: 42s
        graceTimeOut: 42s
      respondingTimeouts:
        readTimeout: 5m
        writeTimeout: 10m
        idleTimeout: 5m

  websecure:
    address: ":443"
    transport:
      lifeCycle:
        requestAcceptGraceTimeout: 42s
        graceTimeOut: 42s
      respondingTimeouts:
        readTimeout: 5m
        writeTimeout: 10m
        idleTimeout: 5m

certificatesResolvers:
  letsencrypt-duck:
    acme:
      email: jiayangchai1203@gmail.com
      storage: /etc/traefik/acme-duck.json
      dnsChallenge:
        provider: duckdns
        disablePropagationCheck: true
        delayBeforeCheck: 60s
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

  letsencrypt-dynu:
    acme:
      email: jiayangchai1203@gmail.com
      storage: /etc/traefik/acme-dynu.json
      dnsChallenge:
        provider: dynu
        disablePropagationCheck: true
        delayBeforeCheck: 60s
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"

tls:
  stores:
    default:
      defaultCertificate:
        certResolver: letsencrypt-duck

api:
  insecure: true
  dashboard: true

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

log:
  level: DEBUG

headers:
  forwardedHeaders:
    insecure: true
