version: "3.8"
services:
  cloudreve:
    container_name: cloudreve
    image: cloudreve/cloudreve:latest
    ports:
      - "5212:5212"
    environment:
      - DB_HOST=postgres
      - DB_NAME=cloudreve
      - DB_PASSWORD=yourpassword
      - DB_PORT=5432
      - DB_TYPE=postgres
      - DB_USER=cloudreve
    volumes:
      - /DATA/AppData/cloudreve/uploads:/cloudreve/uploads
      - /DATA/AppData/cloudreve/config:/cloudreve/config
      - /DATA/AppData/cloudreve/db:/cloudreve/db
    depends_on:
      postgres:
        condition: service_started
    restart: unless-stopped
    network_mode: bridge

  postgres:
    container_name: cloudreve-postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=cloudreve
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_USER=cloudreve
    volumes:
      - /DATA/AppData/cloudreve/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    network_mode: bridge
