version: "3.7"
services:
  cosmos-server:
    cpu_shares: 90
    container_name: cosmos-server
    deploy:
      resources:
        limits:
          memory: 9946M
    environment:
      - COSMOS_SERVER_COUNTRY=MY
      - DOCKER_HOST=unix:///var/run/docker.sock
      - MONGO_URI=mongodb://root:root@mongodb:27017/mongodb  # MongoDB connection string
    hostname: cosmos-server
    image: azukaar/cosmos-server:latest
    ports:
      - mode: ingress
        target: 80
        published: "2080"
        protocol: tcp
      - mode: ingress
        target: 443
        published: "2443"
        protocol: tcp
      - mode: ingress
        target: 4242
        published: "4242"
        protocol: udp
    privileged: true
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /DATA/AppData/cosmos-server/mnt/host:/mnt/host
      - /DATA/AppData/cosmos-server/config:/config
    network_mode: bridge

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
