version: '3.7'

services:
  database:
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    container_name: immich-postgres
    command:
      - postgres
      - -c
      - shared_preload_libraries=vectors.so
      - -c
      - search_path="", public, vectors
      - -c
      - logging_collector=on
      - -c
      - max_wal_size=2GB
      - -c
      - shared_buffers=512MB
      - -c
      - wal_compression=on
    environment:
      - POSTGRES_DB=immich
      - POSTGRES_INITDB_ARGS=--data-checksums
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - /DATA/AppData/immich/pgdata:/var/lib/postgresql/data
    networks:
      - immich

  immich-server:
    image: altran1502/immich-server:pr-14759
    container_name: immich-server
    depends_on:
      database:
        condition: service_started
      redis:
        condition: service_started
    environment:
      - DB_DATABASE_NAME=immich
      - DB_PASSWORD=postgres
      - DB_USERNAME=postgres
    ports:
      - "2283:2283"
    volumes:
      - /DATA/Gallery/immich:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    networks:
      - immich

  redis:
    image: docker.io/redis:6.2-alpine@sha256:2ba50e1ac3a0ea17b736ce9db2b0a9f6f8b85d4c27d5f5accc6a416d8f42c6d5
    container_name: immich-redis
    volumes:
      - /DATA/AppData/immich/redis:/data
    networks:
      - immich

networks:
  immich:
    name: immich
