version: "3.8"

services:
  database:
    image: tensorchord/pgvecto-rs:pg16-v0.2.0
    container_name: immich-postgres
    restart: always
    environment:
      POSTGRES_DB: immich
      POSTGRES_USER: immich
      POSTGRES_PASSWORD: immich
    volumes:
      - /DATA/AppData/immich/pgdata:/var/lib/postgresql/data
    networks:
      - immich

  redis:
    image: redis:7.2.4-alpine
    container_name: immich-redis
    restart: always
    networks:
      - immich

  immich-server:
    image: ghcr.io/immich-app/immich-server:release
    container_name: immich-server
    restart: unless-stopped
    depends_on:
      - database
      - redis
    environment:
      DB_DATABASE_NAME: immich
      DB_USERNAME: immich
      DB_PASSWORD: immich
      DB_HOSTNAME: immich-postgres
      DB_PORT: 5432
      REDIS_HOSTNAME: immich-redis
    volumes:
      - /DATA/AppData/immich/upload:/usr/src/app/upload
    ports:
      - "2283:3001"
    networks:
      - immich

networks:
  immich:
