version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kuala_Lumpur
    volumes:
      - type: bind
        source: /DATA/AppData/jellyfin/config
        target: /config
      - type: bind
        source: /DATA/AppData/jellyfin/cache
        target: /cache
      - type: bind
        source: /DATA/AppData/jellyfin/media/Hong Kong Drama
        target: /Hong Kong Drama
      - type: bind
        source: /DATA/AppData/jellyfin/media/China Drama
        target: /China Drama
      - type: bind
        source: /DATA/AppData/jellyfin/media/China Movies
        target: /China Movie
      - type: bind
        source: /DATA/AppData/jellyfin/media/Singapore Drama
        target: /Singapore Drama
      - type: bind
        source: /DATA/AppData/jellyfin/media/Movies
        target: /Movies
      - type: bind
        source: /DATA/AppData/jellyfin/media/Shows
        target: /Shows
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
