version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /srv/dev-disk-by-uuid-b2690224-c1a3-4024-946d-ca4e02714936/appdata/jellyfin/config:/config:rw
      - /srv/dev-disk-by-uuid-b2690224-c1a3-4024-946d-ca4e02714936/appdata/jellyfin/cache:/cache:rw
      - /srv/dev-disk-by-uuid-b2690224-c1a3-4024-946d-ca4e02714936/appdata/jellyfin/media/Hong Kong Drama:/Hong Kong Drama
      - /srv/dev-disk-by-uuid-b2690224-c1a3-4024-946d-ca4e02714936/appdata/jellyfin/media/China Drama:/China Drama
      - /srv/dev-disk-by-uuid-b2690224-c1a3-4024-946d-ca4e02714936/appdata/jellyfin/media/China Movie:/China Movie
      - /srv/dev-disk-by-uuid-b2690224-c1a3-4024-946d-ca4e02714936/appdata/jellyfin/media/Singapore Drama:/Singapore Drama
      - /srv/dev-disk-by-uuid-b2690224-c1a3-4024-946d-ca4e02714936/appdata/jellyfin/media/Movies:/Movies
      - /srv/dev-disk-by-uuid-b2690224-c1a3-4024-946d-ca4e02714936/appdata/jellyfin/media/Shows:/Shows
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped