version: '3.8'

services:
  nextcloud:
    container_name: nextcloud
    image: nextcloud:latest
    restart: unless-stopped
    depends_on:
      onlyoffice:
        condition: service_started
      postgres:
        condition: service_started
      redis:
        condition: service_started
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_USER=nextcloud
      - REDIS_HOST=redis
    ports:
      - "8080:80"
    volumes:
      - /DATA/AppData/NextCloud/nextcloud:/var/www/html       # Core files
      - /DATA/AppData/NextCloud/apps:/var/www/html/apps       # Apps
      - /DATA/AppData/NextCloud/config:/var/www/html/config   # Config
      - /DATA/AppData/NextCloud/data:/var/www/html/data       # User Data
    networks:
      - nextcloud_net

  onlyoffice:
    container_name: onlyoffice
    image: onlyoffice/documentserver:latest
    restart: unless-stopped
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=supersecure
    ports:
      - "8082:80"
    volumes:
      - /DATA/AppData/NextCloud/onlyoffice:/var/www/onlyoffice/data
    networks:
      - nextcloud_net

  postgres:
    container_name: nextcloud-db
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_USER=nextcloud
    volumes:
      - /DATA/AppData/NextCloud/postgresql:/var/lib/postgresql/data
    networks:
      - nextcloud_net

  redis:
    container_name: nextcloud-redis
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - /DATA/AppData/NextCloud/redis:/data
    networks:
      - nextcloud_net

networks:
  nextcloud_net:
    driver: bridge
