version: '3.9'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password  # Change this to a secure password
      MYSQL_DATABASE: cells
      MYSQL_USER: pydio
      MYSQL_PASSWORD: pydio  # Change this to a secure password
    networks:
      - pydio_network
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"

  pydio:
    image: pydio/cells:latest
    container_name: pydio
    environment:
      CELLS_BIND: "0.0.0.0:8081"
      CELLS_NO_SSL: "1"
    depends_on:
      - mariadb
    networks:
      - pydio_network
    ports:
      - "8081:8081"
    volumes:
      - pydio_data:/var/cells/data
      - pydio_working:/var/cells/working
      - pydio_conf:/var/cells/conf
      - pydio_logs:/var/cells/logs

networks:
  pydio_network:
    driver: bridge

volumes:
  mariadb_data:
  pydio_data:
  pydio_working:
  pydio_conf:
