version: '3.9'

services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    environment:
      - MYSQL_DATABASE=cells
      - MYSQL_USER=pydio
      - MYSQL_PASSWORD=Matrex2003
      - MYSQL_ROOT_PASSWORD=Matrex2003
    ports:
      - "3306:3306"
    volumes:
      - /DATA/AppData/Pydio/var/lib/mysql:/var/lib/mysql
    networks:
      - pydio_network
    restart: unless-stopped

  pydio:
    container_name: pydio
    image: pydio/cells:latest
    depends_on:
      mariadb:
        condition: service_started
    environment:
      - CELLS_BIND=0.0.0.0:8081
      - CELLS_EXTERNAL=https://pyd.matrex.gleeze.com
      - CELLS_NO_TLS=true
    ports:
      - "8082:8081"
    volumes:
      - /DATA/AppData/Pydio/var/cells/data:/var/cells/data
      - /DATA/AppData/Pydio/var/cells/working:/var/cells/working
      - /DATA/AppData/Pydio/var/cells/conf:/var/cells/conf
    networks:
      - pydio_network
    restart: unless-stopped

networks:
  pydio_network:
    driver: bridge
