services:
    speedtest-tracker:
        image: lscr.io/linuxserver/speedtest-tracker:latest
        restart: unless-stopped
        container_name: speedtest-tracker
        ports:
            - 800:80
            - 1443:443
        environment:
            - PUID=1000
            - PGID=1000
            - APP_KEY=base64:HLBiBYhUwwPRrg490zzJ0hxRv8xtihymYN3SS7Exx54=
            - MARIADB_CONNECTION=mariadb
            - MARIADB_HOST=mariadb
            - MARIADB_PORT=3306
            - MARIADB_DATABASE=speedtest
            - MARIADB_USERNAME=speedtest
            - MARIADB_PASSWORD=password
            - DISPLAY_TIMEZONE=Asia/Kuala_Lumpur
        volumes:
            - /path/to/data:/config
            - /path/to-custom-ssl-keys:/config/keys
        depends_on:
            - mariadb
    mariadb:
        image: mariadb:latest
        restart: always
        environment:
            - MARIADB_DATABASE=speedtest
            - MARIADB_USER=speedtest
            - MARIADB_PASSWORD=password
            - MARIADB_ROOT_PASSWORD=password
        volumes:
            - speedtest-db:/var/lib/mysql
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            interval: 5s
            retries: 3
            timeout: 5s
volumes:
  speedtest-db:
