version: "3.8"
services:
  nextcloud:
    container_name: nextcloud
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    image: nextcloud:fpm
    restart: unless-stopped
    volumes:
      - /DATA/AppData/NextCloud/nextcloud:/var/www/html
      - /DATA/AppData/NextCloud/apps:/var/www/html/apps
      - /DATA/AppData/NextCloud/config:/var/www/html/config
      - /DATA/AppData/NextCloud/data:/var/www/html/data
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_USER=nextcloud
      - REDIS_HOST=redis
    networks:
      - nextcloud_net

  cron:
    container_name: nextcloud-cron
    depends_on:
      nextcloud:
        condition: service_started
    entrypoint:
      - /cron.sh
    image: nextcloud:fpm
    restart: unless-stopped
    volumes:
      - /DATA/AppData/NextCloud/nextcloud:/var/www/html
    networks:
      - nextcloud_net

  nginx:
    container_name: nextcloud-nginx
    depends_on:
      nextcloud:
        condition: service_started
    image: nginx:alpine
    ports:
      - "8080:80"
    restart: unless-stopped
    volumes:
      - /DATA/AppData/NextCloud/nextcloud:/var/www/html
      - /DATA/AppData/NextCloud/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - nextcloud_net

  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_USER=nextcloud
    volumes:
      - /DATA/AppData/NextCloud/postgresql:/var/lib/postgresql/data
    networks:
      - nextcloud_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nextcloud"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: redis
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - /DATA/AppData/NextCloud/redis:/data
    networks:
      - nextcloud_net

networks:
  nextcloud_net:
    driver: bridge
