version: 3.8
services:
  cron:
    container_name: nextcloud-cron
    depends_on:
      nextcloud:
        condition: service_started
    entrypoint:
      - /cron.sh
    image: nextcloud:fpm
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/NextCloud/nextcloud
        target: /var/www/html
    networks:
      - nextcloud_net

  nextcloud:
    container_name: nextcloud
    depends_on:
      onlyoffice:
        condition: service_started
      postgres:
        condition: service_started
      redis:
        condition: service_started
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_USER=nextcloud
      - REDIS_HOST=redis
    image: nextcloud:fpm
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/NextCloud/nextcloud
        target: /var/www/html
      - type: bind
        source: /DATA/AppData/NextCloud/apps
        target: /var/www/html/apps
      - type: bind
        source: /DATA/AppData/NextCloud/config
        target: /var/www/html/config
      - type: bind
        source: /DATA/AppData/NextCloud/data
        target: /var/www/html/data
    networks:
      - nextcloud_net

  nginx:
    container_name: nextcloud-nginx
    depends_on:
      nextcloud:
        condition: service_started
    image: nginx:alpine
    ports:
      - target: 80
        published: "8080"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/NextCloud/nextcloud
        target: /var/www/html
      - type: bind
        source: /DATA/AppData/NextCloud/nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
    networks:
      - nextcloud_net

  onlyoffice:
    container_name: onlyoffice
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=supersecure
    image: onlyoffice/documentserver:latest
    ports:
      - target: 80
        published: "8082"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/NextCloud/onlyoffice
        target: /var/www/onlyoffice/data
    networks:
      - nextcloud_net

  postgres:
    container_name: nextcloud-db
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_USER=nextcloud
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/NextCloud/postgresql
        target: /var/lib/postgresql/data
    networks:
      - nextcloud_net

  redis:
    container_name: nextcloud-redis
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/NextCloud/redis
        target: /data
    networks:
      - nextcloud_net

networks:
  nextcloud_net:
    driver: bridge
