name: homepage
services:
  homepage:
    cpu_shares: 90
    command: []
    container_name: homepage
    deploy:
      resources:
        limits:
          memory: 9915M
        reservations:
          memory: "134217728"
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=192.168.3.51:3000
      - PGID=1000
      - PUID=1000
    image: ghcr.io/gethomepage/homepage:latest
    labels:
      icon: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/homepage/icon.png
    ports:
      - target: 3000
        published: "3000"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/homepage/config
        target: /app/config
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  author: Cp0204
  category: WEB
  description:
    en_us: A modern, fully static, fast, secure fully proxied, highly customizable
      application dashboard with integrations for over 100 services and
      translations into multiple languages. Easily configured via YAML files or
      through docker label discovery.
    zh_cn: 一个现代化的、完全静态的、快速的、安全的、完全代理的、高度可定制的应用程序仪表板，集成了100多种服务和多种语言的翻译。通过YAML文件或Docker标签发现轻松配置。
  developer: benphelps
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/homepage/icon.png
  index: /
  is_uncontrolled: false
  main: homepage
  port_map: "3000"
  scheme: http
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/homepage/screenshot-1.png
  store_app_id: homepage
  tagline:
    en_us: A highly customizable homepage
    zh_cn: 高度可定制的主页
  title:
    custom: ""
    en_us: homepage
    zh_cn: homepage
